name: ci/cd for college website

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.dockerignore'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1 

      - name: login to amazon public ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public


      - name: build, tag and push image to ecr
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_ALIAS: ${{secrets.AWS_ECR_ALIAS}}
          ECR_REPOSITORY: ${{secrets.AWS_ECR_REPOSITORY}}
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t $ECR_REPOSITORY .
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_ALIAS/$ECR_REPOSITORY:latest
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_ALIAS/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_ALIAS/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_ALIAS/$ECR_REPOSITORY:$IMAGE_TAG

      - name: update ecs with latest image
        run: |
          aws ecs update-service \
            --cluster ${{secrets.ECS_CLUSTER}} \
            --service ${{secrets.ECS_SERVICE}} \
            --force-new-deployment \
            --region ap-south-1

